[package]
name = "from-c-use-rust"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "from_c_use_rust"
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.27"

[dependencies]
